### ISSUE TITLE
Title bar is 2px larger than the window on Ubuntu 16.04

### ISSUE THREAD

**Issue by golimpio** [tista500/Adapta#54]
Title bar is 2px larger (1px each side) than the window itself (it might be a border issue specific to the unity CSS).

It's noticeable on GTK2 applications (e.g. gedit, sublime), but also happen on dialogues: 

![screenshot-dialog](https://cloud.githubusercontent.com/assets/138681/14563053/45bb7bc6-0363-11e6-8d8d-4c4e56a4efff.png)

**Text editor (gedit):**

![screenshot-gedit](https://cloud.githubusercontent.com/assets/138681/14563069/5412dba6-0363-11e6-855c-067ae6604c06.png)

**Sublime:**

![screenshot-sublime](https://cloud.githubusercontent.com/assets/138681/14563074/57f44688-0363-11e6-8bcb-0c37aff1912b.png)

**Environment:**
* Ubuntu 16.04
* Latest Adapta from git

**Comment by tista500** [comment]
@golimpio,

I've committed the 1st trial for this issue, so please check if this could solve the issue...

Regards.

**Comment by golimpio** [comment]
@tista500, it looks good now...thank you!!

![dialog-screenshot](https://cloud.githubusercontent.com/assets/138681/14564526/47dc9938-036a-11e6-8e3f-ed1c57eb09a9.png)

![atom-screenshot](https://cloud.githubusercontent.com/assets/138681/14564530/4b62460c-036a-11e6-89ff-aba25d8062df.png)

![sublime-screenshot](https://cloud.githubusercontent.com/assets/138681/14564532/4f89d934-036a-11e6-8bc7-5967b98b0415.png)

**Comment by tista500** [comment]
OK. Good...

Regards.

**Comment by golimpio** [comment]
@tista500 just to let you know that this issue is back somehow.

cheers!!

**Comment by golimpio** [comment]
@tista500 never mind, please ignore my last comment on this issue. I didn't see any change that would have broken this and decided to reboot my system.

After rebooting, everything is back to normal.

I should have done it before commenting, I apologize.

Cheers!!
